name: Deploy Node.js App to EC2

on:
  push:
    branches:
      - main  # Menjalankan workflow ketika ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest  # Menjalankan di runner GitHub Actions berbasis Ubuntu

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}  # Menambahkan session token
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create EC2 Instance
        id: ec2_create
        run: |
          # Membuat instance EC2 menggunakan AWS CLI
          INSTANCE_ID=$(aws ec2 run-instances --image-id ami-0df8c184d5f6ae949 --count 1 --instance-type t2.micro --key-name vockey --security-group-ids sg-0ed43e7ec526488de --subnet-id subnet-09de9002777e220c2 --query "Instances[0].InstanceId" --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
        
      - name: Wait for EC2 Instance to be Running
        run: |
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID

      - name: Get Public IP of EC2 Instance
        id: ec2_ip
        run: |
          PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Set up SSH key from GitHub Secrets
        run: |
          # Membuat direktori .ssh jika belum ada
          mkdir -p ~/.ssh
          
          # Menyimpan SSH private key dari GitHub Secrets ke file sementara
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Memberikan hak akses yang tepat pada file SSH

      - name: Install Node.js and Dependencies
        run: |
          # SSH ke EC2 instance dan install Node.js
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@$PUBLIC_IP << 'EOF'
            sudo yum update -y
            # curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
            sudo yum install -y nodejs git
            sudo git clone https://github.com/dihkaw/showipserverwithnodejs.git
            cd showipserverwithnodejs
            sudo npm install
            sudo npm install -g pm2
            sudo pm2 start index.js
          EOF
